<a href="https://colab.research.google.com/github/ChityalaRahul/Generative-AI_B40/blob/main/Assignment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adadelta
from tensorflow.keras.utils import to_categorical



data = pd.read_csv("winequality-red.csv")
X, y = data.drop('quality', axis=1).values, data['quality'].values

num_classes = len(np.unique(y))
y = y - min(y)

y_categorical = to_categorical(y, num_classes=num_classes)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_categorical, test_size=0.2, random_state=42)

# Build and train ANN model
model = Sequential([
    Dense(16, input_dim=X_train.shape[1], activation='relu'),
    Dense(20, activation='relu'),
    Dense(25, activation='relu'),
    Dense(10, activation='relu'),
    Dense(num_classes, activation='softmax')
])
model.compile(optimizer=Adadelta(), loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=50, batch_size=64, validation_split=0.2)
model.save("wine_quality_model.h5")

# Evaluate and calculate metrics
model = load_model("wine_quality_model.h5")
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")
y_pred = np.argmax(model.predict(X_test), axis=-1)
y_test_labels = np.argmax(y_test, axis=-1)
print("Confusion Matrix:\n", confusion_matrix(y_test_labels, y_pred))
print("Classification Report:\n", classification_report(y_test_labels, y_pred, zero_division=1))

# Deploy and predict quality
def predict_quality(input_data):
    model = load_model("wine_quality_model.h5")
    input_data = scaler.transform(np.array(input_data).reshape(1, -1))
    prediction = np.argmax(model.predict(input_data), axis=-1)
    return prediction[0] + min(data['quality'])

# Example usage
sample_data = [7.4, 0.7, 0.0, 1.9, 0.076, 11, 34, 0.9978, 3.51, 0.56, 9.4]
print("Predicted Quality:", predict_quality(sample_data))


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - accuracy: 0.3837 - loss: 1.7615 - val_accuracy: 0.3398 - val_loss: 1.7591
Epoch 2/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3946 - loss: 1.7602 - val_accuracy: 0.3438 - val_loss: 1.7589
Epoch 3/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3966 - loss: 1.7630 - val_accuracy: 0.3438 - val_loss: 1.7588
Epoch 4/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4305 - loss: 1.7552 - val_accuracy: 0.3438 - val_loss: 1.7587
Epoch 5/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4185 - loss: 1.7548 - val_accuracy: 0.3477 - val_loss: 1.7585
Epoch 6/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3788 - loss: 1.7611 - val_accuracy: 0.3477 - val_loss: 1.7584
Epoch 7/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4293 - loss: 1.7585 - val_accuracy: 0.3477 - val_loss: 1.7582
Epoch 8/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4299 - loss: 1.7496 - val_accuracy: 0.3477 - val_los

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3921 - loss: 1.7542  
Test Accuracy: 0.3688
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Confusion Matrix:
 [[  0   0   1   0   0   0]
 [  0   0  10   0   0   0]
 [  1   2 114   7   6   0]
 [  4   0 119   3   6   0]
 [  3   0  37   0   1   1]
 [  1   0   4   0   0   0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00        10
           2       0.40      0.88      0.55       130
           3       0.30      0.02      0.04       132
           4       0.08      0.02      0.04        42
           5       0.00      0.00      0.00         5

    accuracy                           0.37       320
   macro avg       0.13      0.15      0.10       320
weighted avg       0.30      0.37      0.25       320



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
Predicted Quality: 5
